# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "canal-admin.fullname" . }}
  labels:
    app: {{ include "canal-admin.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ include "canal.chart" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "canal-admin.name" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.canalAdmin.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/canal-admin-init-sql.yaml") . | sha256sum }}
      labels:
        app: {{ include "canal-admin.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: wait-db
        image: smartlyio/wait-for-it
        imagePullPolicy: IfNotPresent
        args: ["$(MYSQL_HOST):3306","--","echo","done"]
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.canalAdmin.config.base.extralConfigMapRef | default "canal-admin" }}
                key: spring.datasource.address
      - name: init-sql
        image: imega/mysql-client
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.canalAdmin.config.base.extralConfigMapRef | default "canal-admin" }}
                key: spring.datasource.username
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.canalAdmin.secret.extralPasswordSecretRef | default "canal-admin" }}
                key: spring.datasource.password
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.canalAdmin.config.base.extralConfigMapRef | default "canal-admin" }}
                key: spring.datasource.address
          - name: MYSQL_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.canalAdmin.config.base.extralConfigMapRef | default "canal-admin" }}
                key: spring.datasource.database
        command:
          - mysql
          - --host=$(MYSQL_HOST)
          - --user=$(MYSQL_USER)
          - --password=$(MYSQL_USER_PASSWORD)
          - --execute=source /docker-entrypoint-initdb.d/canal_manager.sql
        volumeMounts:
          - name: canal-admin-init-sql
            mountPath: /docker-entrypoint-initdb.d/canal_manager.sql
            subPath: canal_manager.sql
      containers:
      - name: canal-admin
        image: {{ .Values.canalAdmin.image }}
        imagePullPolicy: {{ .Values.canalAdmin.pullPolicy }}
        resources:
          {{- toYaml .Values.canalAdmin.resources | nindent 10 }}
        env:
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.canalAdmin.config.base.extralConfigMapRef | default "canal-admin" }}
                key: spring.datasource.username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.canalAdmin.secret.extralPasswordSecretRef | default "canal-admin" }}
                key: spring.datasource.password
          - name: SPRING_DATASOURCE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.canalAdmin.config.base.extralConfigMapRef | default "canal-admin" }}
                key: spring.datasource.address
          - name: SPRING_DATASOURCE_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.canalAdmin.config.base.extralConfigMapRef | default "canal-admin" }}
                key: spring.datasource.database
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.canalAdmin.config.base.extralConfigMapRef | default "canal-admin" }}
                key: server.port
          - name: CANAL_ADMINUSER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.canalAdmin.config.base.extralConfigMapRef | default "canal-admin" }}
                key: canal.adminUser
          - name: CANAL_ADMINPASSWD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.canalAdmin.config.base.extralConfigMapRef | default "canal-admin" }}
                key: canal.adminPasswd
        ports:
        - containerPort:  8089
          protocol: TCP
          name: {{ include "canal-admin.fullname" . }}
        volumeMounts:
        {{- if .Values.canalAdmin.localtimeHostPath.enabled }}
        - name: localtime
          mountPath: /etc/localtime
        {{- end }}
        - name: logs
          mountPath: /canal-admin/logs
      volumes:
        {{- if .Values.canalAdmin.localtimeHostPath.enabled }}
        - name: localtime
          hostPath:
            path: /etc/localtime
        {{- end }}
        - name: canal-admin-init-sql
          configMap:
            name: {{ .Values.canalAdmin.config.initsql.extralConfigMapRef | default "canal-admin-init-sql" }} 
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "canal-admin.fullname" . }}