{{- if not .Values.canalServer.secret.extralPasswordSecretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canal-server.fullname" . }}
  labels:
    app: {{ include "canal-server.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ include "canal.chart" . }}
type: Opaque
data:
  canal.admin.passwd: {{ .Values.canalServer.secret.canalAdminPasswd | b64enc }}
{{- end }}