{{- if not .Values.canalAdmin.secret.extralPasswordSecretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "canal-admin.fullname" . }}
  labels:
    app: {{ include "canal-admin.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ include "canal.chart" . }}
type: Opaque
data:
  spring.datasource.password: {{ .Values.canalAdmin.secret.springDatasourcePassword | b64enc | quote }}
{{- end }}