# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource
{{- if .Values.canalAdmin.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "canal-admin.fullname" . }}
  labels:
    app: {{ include "canal-admin.name" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ include "canal.chart" . }}
  {{- with .Values.canalAdmin.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.canalAdmin.ingress.className }}
  {{- if .Values.canalAdmin.ingress.tls }}
  tls:
  {{- range .Values.canalAdmin.ingress.tls }}
  - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.canalAdmin.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "canal-admin.fullname" . }}
            port:
              number: 80
{{- end }}